spring:
  application:
    name: Smart Food Street
  # -----------------------
  # Database MYSQL
  # -----------------------
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # -----------------------
  #   Set time zone
  # -----------------------
  jackson:
    time-zone: Asia/Ho_Chi_Minh

  # -----------------------
  #   Set time zone
  # -----------------------
  data:
    redis:
      host: localhost # Trỏ về localhost vì Docker đã map port 6379:6379
      port: 6379

  # -----------------------
  #   Cloudinary
  # -----------------------
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  # -----------------------
  #   Unicode + Mail
  # -----------------------
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        mime:
          charset: UTF-8
          allow utf8: true
        smtp:
          auth: true
          starttls:
            enable: true

  # -----------------------
  #   DEBUG
  # -----------------------
  logging:
    level:
      org.springframework.security: DEBUG

  # -----------------------
  #   API KEY GEMINI
  # -----------------------
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://api.openai.com
      enable: false
    vectors tore:
      jdbc:
        initialize-schema: never

# -----------------------
# Server
# -----------------------
server:
  forward-headers-strategy: framework
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
  # address: 0.0.0.0

# -----------------------
#   JWT Settings
# -----------------------
jwt:
  secret: ${JWT_SECRET}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in second

# -----------------------
#   Cloudinary Keys
# -----------------------
cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_SECRET}